# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SOS
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Script of Scripts, a lightweight workflow system for the creation of readable workflows
baseurl: "/sos/" # the subpath of your site, e.g. /blog
url: 

# Social media profiles - feel free to add more here
twitter_username: bopeng
github_username:  bopeng
facebook_username: bopeng
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
address_street: 1400 Pressler St
address_city: Houston
address_state: TX
address_zip: 77030

# Build settings
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed


highlighter: rouge
markdown: kramdown


kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


collections:
  tutorial:
  documentation:


include: 
  - .htaccess
exclude: 
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp


